// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Context;

#nullable disable

namespace API_AdocaoPets.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20250529204406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("API_AdocaoPets.src.Models.Canil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("local")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("numCaes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numGatos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numPets")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Canis", (string)null);
                });

            modelBuilder.Entity("API_AdocaoPets.src.Models.Contabilidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetsId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("valorMedioRacao")
                        .HasColumnType("REAL");

                    b.Property<double>("valorMedioVac")
                        .HasColumnType("REAL");

                    b.Property<double>("valorMedioVet")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.HasIndex("PetsId");

                    b.ToTable("Contabilidades", (string)null);
                });

            modelBuilder.Entity("API_AdocaoPets.src.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanilId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PCD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vacinado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("porte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanilId");

                    b.ToTable("Pets", (string)null);
                });

            modelBuilder.Entity("API_AdocaoPets.src.Models.Contabilidade", b =>
                {
                    b.HasOne("API_AdocaoPets.src.Models.Pet", "Pet")
                        .WithOne("Contabilidade")
                        .HasForeignKey("API_AdocaoPets.src.Models.Contabilidade", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AdocaoPets.src.Models.Pet", "Pets")
                        .WithMany()
                        .HasForeignKey("PetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("API_AdocaoPets.src.Models.Pet", b =>
                {
                    b.HasOne("API_AdocaoPets.src.Models.Canil", "Canil")
                        .WithMany("Pets")
                        .HasForeignKey("CanilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canil");
                });

            modelBuilder.Entity("API_AdocaoPets.src.Models.Canil", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("API_AdocaoPets.src.Models.Pet", b =>
                {
                    b.Navigation("Contabilidade");
                });
#pragma warning restore 612, 618
        }
    }
}
